---
title: "Code_Antoine"
output: html_document
date: "2024-10-25"
---

```{r}
library(Seurat)
mergedDataSet=readRDS(file = "~/Downloads/merged_dataset_clust.rds")
viper_results=readRDS("~/Downloads/viper_results.rds")
```

Metacells
```{r}
library(WGCNA)
library(hdWGCNA)

seurat_obj <- SetupForWGCNA(
  mergedDataSet,
  gene_select = "fraction", # the gene selection approach
  fraction = 0.05, # fraction of cells that a gene needs to be expressed in order to be included
  wgcna_name = "MetaCells" # the name of the hdWGCNA experiment
)

# construct metacells  in each group
seurat_obj <- MetacellsByGroups(
  seurat_obj = seurat_obj,
  group.by = c("SCT_snn_res.0.1", "sample"), # specify the columns in seurat_obj@meta.data to group by
  reduction = 'umap', # select the dimensionality reduction to perform KNN on
  k = 25, # nearest-neighbors parameter
  max_shared = 10, # maximum number of shared cells between two metacells
  ident.group = 'SCT_snn_res.0.1' # set the Idents of the metacell seurat object
)

# normalize metacell expression matrix:
seurat_obj <- NormalizeMetacells(seurat_obj)
```

Clustering by RNA
```{r}
mergedDataSet = FindVariableFeatures(mergedDataSet, nfeatures = 2000)
mergedDataSet <- RunPCA(mergedDataSet, verbose = FALSE)
ElbowPlot(mergedDataSet, ndims = 30)
mergedDataSet <- FindNeighbors(mergedDataSet, dims = 1:20, verbose = FALSE)
mergedDataSet <- FindClusters(mergedDataSet, verbose = FALSE, resolution = 0.1)
mergedDataSet <- RunUMAP(mergedDataSet, dims = 1:20, verbose = FALSE)
DimPlot(mergedDataSet, reduction = "umap", label = T) 
```

```{r}
mergedDataSet@assays$TF = CreateAssayObject(counts = viper_results)
DefaultAssay(mergedDataSet) = 'TF' #specify you want to use the TF matrix
mergedDataSet@assays$TF@scale.data <- viper_results #Adding the data 
```

Clustering
```{r}
DefaultAssay(mergedDataSet) = "TF"
mergedDataSet@assays$TF@key <- "TF_"
mergedDataSet = FindVariableFeatures(mergedDataSet)
mergedDataSet <- RunPCA(mergedDataSet, verbose = FALSE)
ElbowPlot(mergedDataSet, ndims = 10)
mergedDataSet <- FindNeighbors(mergedDataSet, dims = 1:10, verbose = FALSE, graph.name = c("TF_nn", "TF_snn"))
mergedDataSet <- FindClusters(mergedDataSet, verbose = FALSE, resolution = 0.3, graph.name = "TF_snn")
mergedDataSet <- RunUMAP(mergedDataSet, dims = 1:10, verbose = FALSE)
DimPlot(mergedDataSet, reduction = "umap", label = T) 
```

