---
title: "Heatmap_Chloe"
output: html_document
date: "2025-03-15"
---

Load data
```{r}
anova_tests = read.csv("~/Downloads/test_marcelo.csv")
library(dplyr)
```

Preprocessing
```{r}
column1 = c()
column2 = c()
for(i in 1:nrow(anova_tests)){
  column1 = c(column1, gsub("^\\s+|\\s+$", "", stringr::str_split(anova_tests$Tukey.s.multiple.comparisons.test, "vs")[[i]][1]))
  column2 = c(column2, gsub("^\\s+|\\s+$", "", gsub("\\.", "", stringr::str_split(anova_tests$Tukey.s.multiple.comparisons.test, "vs")[[i]][2])))
}

matrix_df <- anova_tests %>%
  dplyr::mutate(x = column1, y = column2) %>%
  dplyr::group_by(x, y) %>%
  dplyr::summarise(value = mean(Predicted..LS..mean.diff.), .groups = "drop") %>%
  dplyr::bind_rows(rename(., x = y, y = x)) %>%
  tidyr::pivot_wider(names_from = y, values_from = value) %>%
  tibble::column_to_rownames("x") %>%
  dplyr::select(all_of(rownames(.))) %>%
  as.matrix()

pval_df <- anova_tests %>%
  dplyr::mutate(x = column1, y = column2) %>%
  dplyr::group_by(x, y) %>%
  dplyr::summarise(value = paste(na.omit(unique(Summary)), collapse = ", "), .groups = "drop") %>%
  dplyr::bind_rows(rename(., x = y, y = x)) %>%
  tidyr::pivot_wider(names_from = y, values_from = value) %>%
  tibble::column_to_rownames("x") %>%
  dplyr::select(all_of(rownames(.))) %>%
  as.matrix()


matrix_df = as.matrix(matrix_df)
pval_df = as.matrix(pval_df)

#textMatrix = pval_df
#textMatrix = pval_df
idx = which(is.na(pval_df) | pval_df == "ns")

for (i in idx) {
  pval_df[i] = NA
  matrix_df[i] = NA
}

textMatrix = pval_df

```

Change pvalues to numeric
```{r}
pval_df_numeric <- matrix(NA, nrow = nrow(pval_df), ncol = ncol(pval_df))
rownames(pval_df_numeric) <- rownames(pval_df)
colnames(pval_df_numeric) <- colnames(pval_df)

for (i in seq_along(pval_df)) {
  if (grepl("\\*\\*\\*\\*", pval_df[i])) {
    pval_df_numeric[i] <- 4  # Assign 4 to '****'
  } else if (grepl("\\*\\*\\*", pval_df[i])) {
    pval_df_numeric[i] <- 3  # Assign 3 to '***'
  } else if (grepl("\\*\\*", pval_df[i])) {
    pval_df_numeric[i] <- 2  # Assign 2 to '**'
  } else if (grepl("\\*", pval_df[i])) {
    pval_df_numeric[i] <- 1  # Assign 1 to '*'
  }else {
    pval_df_numeric[i] <- NA  # Keep NA for non-significant values
  }
}

```

Heatmap
```{r}
pdf("Heatmap_Chloe.pdf", width = 18, height = 15)
par(mar = c(25, 20, 3, 3))
WGCNA::labeledHeatmap(
  Matrix = pval_df_numeric,
  xLabels = colnames(matrix_df),
  yLabels = rownames(matrix_df),
  ySymbols = rownames(matrix_df),
  colorLabels = FALSE,
  colors = c("#EE6677", "#66CCEE", "#AA3377", "#4477AA"),
  textMatrix = textMatrix,  # Keep original significance markers as text
  setStdMargins = FALSE,
  plotLegend = F,
  cex.text = 1,
  main = "Analyse two way anova cellules tumorales et macrophages en meme temps 2D"
)
dev.off()
```

