---
title: "Template_script"
author: "Marcelo Hurtado"
date: "2024-10-22"
output: html_document
---

This script is used as a template for analyze your data with CellTFusion. The user needs to change the paths to specify the location of the following files: counts, traitData.

Set up environment
```{r setup, include=FALSE}
source("src/environment_set.R") #Load functions and packages
set.seed(123) #For reproducibility
```

Input data
```{r}
counts.norm.immucan = read.delim2("~/Downloads/all_cohorts_tpm_27112024.txt", row.names = 1)
rownames(counts.norm.immucan) <- str_replace(rownames(counts.norm.immucan), pattern = ".[0-9]+$", replacement = "")
counts.norm.immucan = convert_ensembl_symbol(counts.norm.immucan)
genes = rownames(counts.norm.immucan)
counts.norm.immucan <- data.frame(apply(counts.norm.immucan, 2, as.numeric))
rownames(counts.norm.immucan) = genes
```

CellTFusion
```{r}
#Drop sample
i = "IMMU.SCCHN1.2110.FIXT.01.RNA.01_._counts_TPM_._11b8d48c5eeeb2b4922cdbb99283ff78"
counts.norm.immucan = counts.norm.immucan[,-which(colnames(counts.norm.immucan)==i)]
counts.scchn1 = counts.norm.immucan[,grep("SCCHN1\\.", colnames(counts.norm.immucan))]

deconv = compute.deconvolution(counts.scchn1, normalized = F, return = T, methods = "CBSX", credentials.mail = "marcelo.hurtado@inserm.fr", credentials.token = "734212f6ad77fc4eea2bdb502792f294", doParallel = T, workers = 3)
```
